version: '3'

services:
  mariadb:
    image: mariadb:latest
    container_name: todo-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - '3307:3306'

volumes:
  mariadb_data:
